### ISSUE TITLE
UnboundLocalError ==  line 192 

### ISSUE THREAD

**Issue by ajaikrishnan** [Atropa-Solanaceae/proXXy#10]
threads is being accessed before it's assigned a value.

To Solve ==  initialize it with a default value or assign a value to it before the if statement.

# Assuming you have a variable named threads defined somewhere in your script
threads = None  # Initialize with a default value or set it based on your logic

**Comment by ajaikrishnan** [comment]
threads = None # Initialize with a default value or set it based on your logic
banner()
print(f"Selected options:\n")
print(f" -- Proxy check: {prox_check}")
if timeout is not None:
print(f" -- Timeout: {timeout}")
if threads is not None:
print(f" -- Threads: {threads}")
confirm_input = input("\nDo you want to continue? (Y/n): ").lower()
if confirm_input == "n":
exit_con()
main(timeout, threads) # Assuming your main function accepts the threads parameter

**Comment by Atropa-Solanaceae** [comment]
I will be rewriting the codebase pretty soon I believe, hopefully to make things much more simple and accessible, and fix any errors like these.

**Comment by ajaikrishnan** [comment]
OKAY :)
