### ISSUE TITLE
Running on headless ubuntu server

### ISSUE THREAD

**Issue by rockydares** [Atropa-Solanaceae/proXXy#12]
This gives an error that looks like,

>  python3 proXXy.py
> HTTP server ListenAndServe: listen tcp: lookup tcp/or re: Servname not supported for ai_socktype
> Traceback (most recent call last):
>   File "/home/proXXy/proXXy.py", line 588, in <module>
>     parameters()
>   File "/home/proXXy/proXXy.py", line 183, in parameters
>     banner()
>   File "/home/proXXy/proXXy.py", line 126, in banner
>     os.system("title proXXy -- by Solanaceae")
>     ^^
> NameError: name 'os' is not defined

**Comment by Atropa-Solanaceae** [comment]
Current version is broken, will update shortly.

**Comment by Atropa-Solanaceae** [comment]
Fixed in new release
