### ISSUE TITLE
utils error while trying to run

### ISSUE THREAD

**Issue by hakanerensen112** [Atropa-Solanaceae/proXXy#15]
![image](https://github.com/Atropa-Solanaceae/proXXy/assets/94652683/b67c159e-ed63-457b-8447-04425a364da0)

**Comment by Atropa-Solanaceae** [comment]
Hm, can you run it with the `-u` flag for me? Just to make sure you have the most updated version, since I made some changes today.

**Comment by hakanerensen112** [comment]
no more needed, ive found 100 datacenter ips all workıng. have e great day.
