### ISSUE TITLE
cannot import name 'utils' from 'build'

### ISSUE THREAD

**Issue by EXXodos911** [Atropa-Solanaceae/proXXy#16]
Traceback (most recent call last):
  File "C:\Users\USER\Tools\proXXy\proXXy.py", line 6, in <module>
    from build import utils
ImportError: cannot import name 'utils' from 'build' (C:\Users\USER\Tools\proXXy\build\__init__.py)

**Comment by Atropa-Solanaceae** [comment]
What operating system are you using?

**Comment by gvoze32** [comment]
I'm running on Windows 10 and got the same problem

**Comment by Atropa-Solanaceae** [comment]
This should now be fixed, update it and test it again.
